env: "local" # local/dev/prod

server:
  address: "localhost:8080"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "10D18E03I13m"
  dbname: "x_clone"
  sslmode: "disable"
